version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: mi_basedatos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_net

volumes:
  postgres_data:

networks:
  postgres_net:
